### PR TITLE
Make UPDATE_LOCATION follow FSA

### LINKED ISSUE #206: Back FSA actions
I'm curious why you decide to move from FSA in 2.x.x

### PR DESCRIPTION
**Pull request by SimenB**
Fix #206

Could use `redux-actions` to create the action creator, but that seems overkill

### CODE REVIEW

**Comment by timdorr** [comment]
Thanks! This is a good start. Can you add the TRANSISTION actions as well?

**Comment by SimenB** [comment]
Ah, didn't bother with it as I thought it was internal.

Use `redux-actions`, or still do it manually?

**Comment by timdorr** [comment]
Spellchecker fail: TRANSITION actions.

**Comment by timdorr** [comment]
Manually. I don't think we need to add another dependency.

**Comment by SimenB** [comment]
@timdorr Done.

**Comment by timdorr** [comment]
Awesome! Thank you!

**Comment by SimenB** [comment]
@timdorr I didn't realize 2.0 was out of beta.

This is a breaking change, isn't it?

**Comment by timdorr** [comment]
Shouldn't really be. The API is the same. Action shapes are internal and
subject to change within the same minor version.

**Comment by SimenB** [comment]
aight :smile:

**Comment by jlongster** [comment]
Well, not sure they are really internal, since people can listen to the `UPDATE_LOCATION` action. This is the sort of thing I hate about semver though, I don't want to release a whole 3.0.0 version just for this, especially since it's a quick change right after 2.0.0.

I don't really know how often people listen to that action, probably not much. We should definitely document it in the changelog though.

**Comment by SimenB** [comment]
Want me to add a PR for the changelog?

**Comment by valscion** [comment]
> Well, not sure they are really internal, since people can listen to the `UPDATE_LOCATION` action.

Yeah, we do that. Glad I checked on the changelog before upgrading from beta version as this would've broke our stuff :sweat_smile: 

I agree that semver sucks in these cases. But I also don't really care at all even if this library's version would change from 2.0 to 3.0 within 4 days. It only tips me off to read the changelog if the major version changes — if there's only one change, it shouldn't be a hassle to upgrade immediately :smile:

I'm just glad I didn't get burned before reading this issue ¯\\\_(ツ)_/¯

**Pull request merged**
