### PR TITLE
Add files fileds to package.json

### PR DESCRIPTION
**Pull request by koba04**
This PR is to includes only necessary files in published tarball.

* Currently

```
-rw-r--r--  0 501    20       2082 12 21 15:58 package/package.json
-rw-r--r--  0 501    20        104 12 21 15:58 package/.npmignore
-rw-r--r--  0 501    20       7045 12 21 14:42 package/README.md
-rw-r--r--  0 501    20       1054 12 21 14:42 package/LICENSE
-rw-r--r--  0 501    20        120 12 21 14:42 package/tests.webpack.js
-rw-r--r--  0 501    20       1194 12 21 14:42 package/karma.conf.js
-rw-r--r--  0 501    20         27 12 21 14:42 package/.eslintrc
-rw-r--r--  0 501    20       1168 12 21 14:42 package/CHANGELOG.md
-rw-r--r--  0 501    20       5660 12 21 15:58 package/lib/index.js
-rw-r--r--  0 501    20      14775 12 21 14:42 package/test/createTests.js
-rw-r--r--  0 501    20        279 12 21 14:42 package/test/browser/index.js
-rw-r--r--  0 501    20        142 12 21 14:42 package/test/node/index.js
-rw-r--r--  0 501    20       4248 12 21 14:42 package/src/index.js
-rw-r--r--  0 501    20         17 12 21 14:42 package/examples/.npmignore
-rw-r--r--  0 501    20        546 12 21 14:42 package/examples/basic/package.json
-rw-r--r--  0 501    20        393 12 21 14:42 package/examples/basic/README.md
-rw-r--r--  0 501    20       1348 12 21 14:42 package/examples/basic/app.js
-rw-r--r--  0 501    20         69 12 21 14:42 package/examples/basic/constants.js
-rw-r--r--  0 501    20        791 12 21 14:42 package/examples/basic/webpack.config.js
-rw-r--r--  0 501    20        257 12 21 14:42 package/examples/basic/actions/count.js
-rw-r--r--  0 501    20        651 12 21 14:42 package/examples/basic/components/App.js
-rw-r--r--  0 501    20        104 12 21 14:42 package/examples/basic/components/Bar.js
-rw-r--r--  0 501    20        100 12 21 14:42 package/examples/basic/components/Foo.js
-rw-r--r--  0 501    20        492 12 21 14:42 package/examples/basic/components/Home.js
-rw-r--r--  0 501    20        165 12 21 14:42 package/examples/basic/components/index.js
-rw-r--r--  0 501    20        219 12 21 14:42 package/examples/basic/index.html
-rw-r--r--  0 501    20        379 12 21 14:42 package/examples/basic/reducers/count.js
-rw-r--r--  0 501    20         63 12 21 14:42 package/examples/basic/reducers/index.js
```

* After

```
➜  tar tvfz redux-simple-router-1.0.1.tgz
-rw-r--r--  0 501    20       2137 12 21 15:49 package/package.json
-rw-r--r--  0 501    20       7045 12 21 14:42 package/README.md
-rw-r--r--  0 501    20       1054 12 21 14:42 package/LICENSE
-rw-r--r--  0 501    20       1168 12 21 14:42 package/CHANGELOG.md
-rw-r--r--  0 501    20       5660 12 21 15:50 package/lib/index.js
```

Thanks.

### CODE REVIEW

**Comment by kjbekkelund** [comment]
Hm, any cons to this? I usually look at code on github if I have issues (e.g. to see `examples/` and so on). I also clone the repo if I want to run the tests and do more debugging. So I'm +1 on this. @jlongster, any strong feelings?

**Comment by kjbekkelund** [comment]
This is basically the same stuff [react does](https://github.com/facebook/react/blob/master/packages/react/package.json), so really shouldn't be a problem

**Comment by jlongster** [comment]
As long as if you npm install straight from the github repo you still get all the files, this sounds good to me.

**Comment by koba04** [comment]
Thanks!

**Comment by neverfox** [comment]
> As long as if you npm install straight from the github repo you still get all the files, this sounds good to me.

You won't. I referenced this in #156.

**Comment by kjbekkelund** [comment]
Yep, definitely doesn't work installing from master, so we should revert this.

```
$ npm install https://github.com/rackt/redux-simple-router.git#master
$ tree node_modules/redux-simple-router 
node_modules/redux-simple-router
├── CHANGELOG.md
├── LICENSE
├── README.md
└── package.json

0 directories, 4 files
```

**Comment by neverfox** [comment]
I don't know of a way to exclude from the tarball and not the install. I expect they're supposed to represent two identical snapshots.

**Pull request merged**
