### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by glennr**

### CODE REVIEW

**Comment by glennr** [comment]
Hi @jlongster  - you'll have to set up a Travis instance for your repo for this PR - and then update the badge URL to point at your build i.e. 

```
[![build status](https://img.shields.io/travis/glennr/redux-simple-router/master.svg?style=flat-square)](https://travis-ci.org/glennr/redux-simple-router)
```

becomes 

```
[![build status](https://img.shields.io/travis/jlongster/redux-simple-router/master.svg?style=flat-square)](https://travis-ci.org/jlongster/redux-simple-router)
```

**Comment by jlongster** [comment]
Thanks a lot. I'll look into this.

**Comment by kjbekkelund** [comment]
@jlongster I was going to take a look at this, but don't seem to have admin access (which is needed to enable travis for a repo). Maybe you could enable, then I'll take a look at getting it running? (Or add access to I can fix)

**Comment by timdorr** [comment]
Turned it on with Travis: https://travis-ci.org/rackt/redux-simple-router I'll get this updated and ready to merge.

**Pull request closed without merging**
