### PR TITLE
updated example app to use middleware

### PR DESCRIPTION
**Pull request by tomatau**
This branches off https://github.com/rackt/redux-simple-router/pull/141 to update the example app

### CODE REVIEW

**Comment by jlongster** [comment]
Thanks!

**Comment by tomatau** [comment]
could you put this on npm with a @next tag or something please?

**Comment by timdorr** [comment]
BTW, this merged into the middleware branch, not master. I'll fix that up now.

**Comment by jlongster** [comment]
Oh, thanks @timdorr! Did it last night right before I my laptop died so I didn't notice. @tomatau what do you mean on npm? The example app? How does putting the example app on npm help?

**Comment by tomatau** [comment]
Apologies, I was referring to the middleware branch that was merged, it still hasn't undergone a version bump right?

**Comment by jlongster** [comment]
Not yet, it's too new to do a version bump. We should let it sit on master for at least a few days to make sure nothing is seriously broken. We also need to update docs, etc

**Comment by kjbekkelund** [comment]
@jlongster Could also use [`dist-tag`](https://docs.npmjs.com/cli/dist-tag) for this. That way it's easier for people to test the latest code. Blog post on it: https://medium.com/greenkeeper-blog/one-simple-trick-for-javascript-package-maintainers-to-avoid-breaking-their-user-s-software-and-to-6edf06dc5617

(Never tried this myself, though)

**Comment by tomatau** [comment]
> with a @next tag

Yep with a dist-tag. So we can try it without having to build it for each project

**Comment by jlongster** [comment]
I can do that. I'm really scared I'm going to accidentally publish 2.0.0 though!

I did this:

* Changed the version in package.json to 2.0.0
* Ran `npm dist-tag add redux-simple-router@2.0.0 next`

It *seemed* to work... now do I run `npm publish --tag=next`? The `dist-tag` seemed odd because I had to pass it the package name and I can't tell how it's correlating the current files in the project to `2.0.0`.

**Comment by kjbekkelund** [comment]
The docs for `dist-tag` are really bad :/ But the video in the blog post demystifies how it works. And yep, what you've done looks correct.

**Comment by kjbekkelund** [comment]
As far as I can tell, you don't actually need to run `npm dist-tag add redux-simple-router@2.0.0 next` for `next`, but only when updating the `latest` tag to `2.0.0` later.

**Comment by jlongster** [comment]
As far as I know `latest` means the actual published version. Meaning anyone who runs `npm install redux-simple-router` is going to get 2.0.0. I thought the point of this was to release it under a tag that people could manually install.

**Comment by kjbekkelund** [comment]
Yep, that's what I meant by "_later_" (i.e. when 2.0.0 is ready to be moved from `next` to `latest`).

But either way, to be entirely sure (given the bad docs), this should do it:

```
npm dist-tag add redux-simple-router@2.0.0 next
npm publish --tag=next
```

**Comment by tomatau** [comment]
@jlongster I think something didn't work

```bash
$ npm info redux-simple-router

{ name: 'redux-simple-router',
  description: 'Ruthlessly simple bindings to keep react-router and redux in sync',
  'dist-tags': { latest: '1.0.2', next: '2.0.0' },
  versions:
   [ '0.0.6',
     '0.0.7',
     '0.0.8',
     '0.0.9',
     '0.0.10',
     '1.0.0',
     '1.0.1',
     '1.0.2' ],
```

```bash
$ npm install redux-simple-router@next

npm ERR! No compatible version found: redux-simple-router@next
npm ERR! Valid install targets:
npm ERR! ["1.0.2","1.0.1","1.0.0","0.0.10","0.0.9","0.0.8","0.0.7","0.0.6"]
npm ERR!
```

Same for `npm i redux-simple-router@2.0.0`

**Comment by jlongster** [comment]
@revgum Assume master will always have breaking changes. I don't know why you would expect otherwise. You don't want `syncHistory` if you are using the latest version from npm; just use it the old way.

It seems like people are happy with this new version, so we should release 2.0.0 soon. I was off work last week so I didn't finish publishing the `next` tag, sorry. I'll try to do that now, and soon we'll get 2.0.0 out.

**Comment by jlongster** [comment]
Ok, I got `npm install redux-simple-router@next` working. It will install 2.0.0 now.

**Comment by tomatau** [comment]
thanks :)

**Comment by revgum** [comment]
Cool! Thanks! I'm totally into what you've built, greatly appreciated!

**Pull request merged**
