### PR TITLE
fix example by updating to 2.0.3

### PR DESCRIPTION
**Pull request by barrystaes**
Fixes fatal runtime error `Uncaught TypeError: middleware.listenForReplays is not a function`.

### CODE REVIEW

**Comment by timdorr** [comment]
That shouldn't matter, as the example aliases to whatever you have checked out above it in git. Check the webpack config.

**Comment by barrystaes** [comment]
I had an issue when using release 2.0.3 so i wanted to compare it to the
example at the 2.0.3 tag in the repo. This is where i encountered the issue.

If its relevant, i only `npm install`ed the example not the main
redux-simple-router package.
Op 18 jan. 2016 15:06 schreef "Tim Dorr" <notifications@github.com>:

**Comment by timdorr** [comment]
Can you make it a caret range then? That should future-proof us against any updates until a major version, in which case there will probably be an updated example anyways.

**Comment by barrystaes** [comment]
Good idea, done.

Ideally the example gets tested prior to a release. I see the resolve code would devs to quickly use their latest version. Nice!

**Comment by timdorr** [comment]
Ideally we could test our examples, [just like Redux does](https://github.com/rackt/redux/blob/master/examples/testAll.js). It's part of the test suite over there. I'd be really jazzed for someone to add those at some point :+1:

**Pull request merged**
