### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by StevenIseki**
update to README to make it easier for new users starting out with the basic example of redux simple router.

### CODE REVIEW

**Comment by mindjuice** [comment]
I get the following error when I try to run the examples after an ``npm install`` in the ``examples/basic`` folder:

```
ERROR in ./app.js
Module parse failed: /Users/kenc/dev/redux-simple-router/node_modules/redux-simple-router/redux-simple-router/examples/basic/app.js Line 8: Unexpected token
You may need an appropriate loader to handle this file type.
| const createHistory = require('history/lib/createHashHistory');
| const { syncHistory, routeReducer } = require('redux-simple-router');
| import { devTools } from 'redux-devtools';
| const { DevTools, DebugPanel, LogMonitor } = require('redux-devtools/lib/react');
|
```

Is this related to your PR?

I tried ``git clone https://github.com/rackt/redux-simple-router/tree/1.0.2``, but got the error:

```
Cloning into '1.0.2'...
fatal: repository 'https://github.com/rackt/redux-simple-router/tree/1.0.2/' not found
```

**Comment by mindjuice** [comment]
Hmmm...just did a ``git checkout tags/1.0.2`` and have the right code now, but get a different error:

```
ERROR in ./app.js
Module build failed: ReferenceError: Unknown plugin "transform-object-assign" specified in "/Users/kenc/dev/redux-simple-router/.babelrc" at 0, attempted to resolve relative to "/Users/kenc/dev/redux-simple-router"
    at /Users/kenc/dev/redux-simple-router/examples/basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:193:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/kenc/dev/redux-simple-router/examples/basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:173:20)
    at OptionManager.mergeOptions (/Users/kenc/dev/redux-simple-router/examples/basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:271:36)
    at OptionManager.addConfig (/Users/kenc/dev/redux-simple-router/examples/basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (/Users/kenc/dev/redux-simple-router/examples/basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:16)
    at OptionManager.init (/Users/kenc/dev/redux-simple-router/examples/basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:412:12)
    at File.initOptions (/Users/kenc/dev/redux-simple-router/examples/basic/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/Users/kenc/dev/redux-simple-router/examples/basic/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/Users/kenc/dev/redux-simple-router/examples/basic/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transpile (/Users/kenc/dev/redux-simple-router/examples/basic/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/kenc/dev/redux-simple-router/examples/basic/node_modules/babel-loader/index.js:88:12)
```

**Comment by StevenIseki** [comment]
Add the follwing .babelrc file to the basic app

{
    "presets": ["es2015"]
}

Then follow the guidance I made in this pull request to the [README](https://github.com/StevenIseki/redux-simple-router/blob/eed89b80899cbf2b79e4757da864cdee83137cf0/examples/basic/README.md) to remove from line 21 onward in the webpack.config.

In my opinion from line 21 onward should be commented out of the webpack.config by default as most users trying the basic example will not be wanting to compile it from source, they are using the basic app as a starting point, so want to use the stable npm published version.

Anyway if you comment that out and add the .babelrc as in the 2 pull requests waiting, all should be fine

**Comment by mindjuice** [comment]
Thanks...the ``.babelrc`` did the trick. :+1:

**Pull request merged**
